import type { Metadata } from "next";
import { Laila, Nunito } from "next/font/google";
import "./globals.css";

const laila = Laila({
  weight: ["500", "600"],
  subsets: ["latin"],
  variable: "--font-laila",
});
const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${laila.variable} ${nunito.variable}`}>{children}</body>
    </html>
  );
}
